#include "d/snd/d_snd_id_mappers_data.h"

#pragma push
#pragma readonly_strings on

const ActorBaseNamePair sActorBaseNamePairs[] = {
    {   "KinokoA",     "Kinoko"},
    {   "KinokoB",     "Kinoko"},
    {   "KinokoC",     "Kinoko"},
    {   "KinokoD",     "Kinoko"},
    {   "SKinoko",     "Kinoko"},
    {      "Tbox",       "TBox"},
    {   "LBmaker",      "LBird"},
    {    "TansuA",      "chest"},
    {    "TansuB",      "chest"},
    {    "TansuC",      "chest"},
    {   "BbsRock",    "RolRock"},
    {   "NpcRvlR",    "NpcBRvl"},
    {   "NpcMWNi", "NpcSalS_A2"},
    {   "NpcMHNi", "NpcSalS_A8"},
    {   "NpcIcgK",    "NpcKbn2"},
    {   "NpcKb2N",    "NpcKbn2"},
    {   "NpcDoNi", "NpcSalS_A1"},
    {   "NpcJkNi", "NpcSalS_A4"},
    {   "NpcAzNi", "NpcSalS_A5"},
    {    "NpcPcs",    "NpcCbFd"},
    {   "NpcAkuH",    "NpcAkum"},
    {   "NpcJkML",    "NpcJkMo"},
    {   "NpcDoML",    "NpcDoMo"},
    {   "NpcSAML",    "NpcSAMo"},
    {"NpcResc_A3",    "NpcResc"},
    {"NpcResc_A4", "NpcResc_A1"},
    {"NpcResc_A5", "NpcResc_A2"},
    {    "NpcGrb",     "NpcGra"},
    {    "NpcGrc",     "NpcGra"},
    {    "NpcGrd",     "NpcGra"},
    {    "OcGrsL",     "OctGrs"},
    {   "NpcOkyu",     "Npckyu"},
    {   "Npckyu1",     "Npckyu"},
    {   "Npckyu2",     "Npckyu"},
    {   "Npckyu3",     "Npckyu"},
    {   "Npckyu4",     "Npckyu"},
    {   "NpcSlKy",     "Npckyu"},
    {   "rpiller",    "rpillar"},
    {       "EOc",        "EBc"},
    {      "EBce",        "EBc"},
    {    "CupA00",      "tware"},
    {    "CupA01",      "tware"},
    {    "CupA02",      "tware"},
    {    "CupB00",      "tware"},
    {    "CupB01",      "tware"},
    {    "CupB02",      "tware"},
    {    "PltA00",      "tware"},
    {    "PltA01",      "tware"},
    {    "PltA02",      "tware"},
    {    "PltB00",      "tware"},
    {    "PltB01",      "tware"},
    {    "PltB02",      "tware"},
    {     "FlvsA",      "tware"},
    {     "FlvsB",      "tware"},
    {     "FlvsC",      "tware"},
    {   "PlntA00",      "tware"},
    {   "PlntA01",      "tware"},
    {     "PlntB",      "tware"},
    {   "PlntC00",      "tware"},
    {   "PlntC01",      "tware"},
    {   "ERupGue",       "EGue"},
    {   "BirdNpc", "BirdCommon"},
    {    "BirdKA", "BirdCommon"},
    {    "BirdKB", "BirdCommon"},
    {     "BirdT", "BirdCommon"},
    {   "NpcBdsw", "BirdCommon"},
    {   "DbidNpc", "BirdCommon"},
    {   "KndBird", "BirdCommon"},
    {    "BrdMob", "BirdCommon"},
    {    "NpcBdz",     "BirdZT"},
    {   "InsctTg",     "Insect"},
    {   "Ladybug",     "Insect"},
    {   "Drgnfly",     "Insect"},
    {    "Beetle",     "Insect"},
    {   "Kuwagat",     "Insect"},
    {    "Grshpr",     "Insect"},
    {    "Cicada",     "Insect"},
    {       "Ant",     "Insect"},
    {   "Butrfly",     "Insect"},
    {    "Mantis",     "Insect"},
    {    "Scarab",     "Insect"},
    {   "Firefly",     "Insect"},
    {   "BcAlArr",    "BcArrow"},
    {   "FShutte",    "FenceIr"},
    {   "BBigBo2",    "BBigBos"},
    {   "BBigBo3",    "BBigBos"},
    {   "NusiNpc",       "Nusi"},
    {     "NusiB",       "Nusi"},
    {   "NpcMoN2",     "NpcMoN"},
    {   "NpcMoEN",    "NpcMole"},
    {    "NpcMoS",    "NpcMoEl"},
    {   "NpcMoT2",     "NpcMoT"},
    {      "BGh2",        "BGh"},
    {   "BGh3Fst",       "BGh3"},
    {   "BGh3Snd",       "BGh3"},
    {   "BGh3Trd",       "BGh3"},
    {   "NpcSlb2",    "NpcSlrb"},
    {   "NpcSlFB",    "NpcSlrb"},
    {   "NpcSlRp",    "NpcSlrb"},
    {   "NpcSlFl",    "NpcSlrb"},
    {   "FlySlrb",    "NpcSlrb"},
    {   "NpcKenT",     "NpcKen"},
    {   "GuardLg",    "SliceLg"},
    {   "SlicePt",    "SliceLg"},
    {   "TrShtCs",    "trlshut"},
    {    "Fmaker",       "Fish"},
    {      "TgTw",      "TWeed"},
    {   "BltObsT",    "Obstacl"},
    {  "Item_A44",   "Item_A43"},
    {  "Item_A45",   "Item_A43"},
    {  "Item_A46",   "Item_A43"},
    {   "PmpknBd",    "Pumpkin"},
    {   "MgPmpkn",    "Pumpkin"},
    {   "CmCloud",   "CumlClud"},
    {   "IslTreB",    "RockSkB"},
    {   "WnLeafA",     "wnleaf"},
    {   "WnLeafB",     "wnleaf"},
    {   "WnLeafC",     "wnleaf"},
    {   "WnLeafD",     "wnleaf"},
    {   "EOrCann",        "EOr"},
};

const s32 sNumActorBaseNamePairs = ARRAY_LENGTH(sActorBaseNamePairs);

#pragma pop
